name: Extract Boot Image

on:
  workflow_dispatch:
    inputs:
      firmware_url:
        description: "MediaFire link"
        required: true

jobs:
  extract:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Disk Space Before
        run: df -h

      - name: Install Required Tools
        run: |
          sudo apt update
          sudo apt install -y p7zip-full aria2 curl

      - name: Get Direct MediaFire Link
        run: |
          echo "Fetching MediaFire page..."
          PAGE=$(curl -L -s "${{ github.event.inputs.firmware_url }}")

          DOWNLOAD_LINK=$(echo "$PAGE" | grep -o 'https://download[^"]*')

          if [ -z "$DOWNLOAD_LINK" ]; then
            echo "Failed to extract direct download link."
            exit 1
          fi

          echo "Direct link found:"
          echo $DOWNLOAD_LINK

          echo "DOWNLOAD_LINK=$DOWNLOAD_LINK" >> $GITHUB_ENV

      - name: Download Firmware (aria2 multi-connection)
        run: |
          aria2c \
          -x 16 -s 16 -k 1M \
          --retry-wait=5 \
          --max-tries=10 \
          "$DOWNLOAD_LINK" \
          -o firmware.rar

      - name: Verify File Size
        run: ls -lh firmware.rar

      - name: Extract Firmware
        run: |
          mkdir firmware
          7z x firmware.rar -ofirmware

      - name: Remove Large RAR (Free Space)
        run: rm -f firmware.rar

      - name: Find boot.img
        run: |
          BOOT_PATH=$(find firmware -type f -name "boot.img" | head -n 1)

          if [ -z "$BOOT_PATH" ]; then
            echo "boot.img not found!"
            exit 1
          fi

          echo "Boot image found at $BOOT_PATH"
          cp "$BOOT_PATH" boot.img

      - name: Show boot.img info
        run: ls -lh boot.img

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot-image
          path: boot_a.img

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: boot-${{ github.run_number }}
          name: Boot Image ${{ github.run_number }}
          files: boot.img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Disk Space After
        run: df -h