name: Extract Kernel Smart (MediaFire)

on:
  workflow_dispatch:
    inputs:
      mediafire_url:
        description: "MediaFire File Page URL"
        required: true

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget curl unzip gzip file grep sed

      - name: Get Direct Download Link
        id: mediafire
        run: |
          page=$(curl -sL "${{ github.event.inputs.mediafire_url }}")
          direct=$(echo "$page" | grep -o 'https://download[^"]*')
          echo "direct_url=$direct" >> $GITHUB_OUTPUT

      - name: Download boot.img
        run: |
          wget -O boot.img "${{ steps.mediafire.outputs.direct_url }}"

      - name: Download Magisk APK
        run: |
          wget https://github.com/topjohnwu/Magisk/releases/download/v30.6/Magisk-v30.6.apk -O Magisk.apk

      - name: Extract magiskboot
        run: |
          unzip -o Magisk.apk lib/x86_64/libmagiskboot.so
          mv lib/x86_64/libmagiskboot.so magiskboot
          chmod +x magiskboot

      - name: Unpack boot.img
        run: |
          ./magiskboot unpack boot.img

      - name: Smart Kernel Processing
        run: |
          mkdir output

          echo "Checking kernel format..."
          file kernel || true

          if file kernel | grep -q "gzip compressed"; then
            echo "Kernel already gzip"
            mv kernel output/Image.gz

          else
            echo "Kernel is RAW, compressing..."
            gzip -c kernel > output/Image.gz
          fi

          if [ -f kernel_dtb ]; then
            echo "DTB found, creating Image.gz-dtb"
            cat output/Image.gz kernel_dtb > output/Image.gz-dtb
          fi

          ls -lah output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-ready
          path: output/